# 1. Functions

In [1]:
def add_numbers(x, y):
    return x + y

add_numbers(1, 2)

3

add_numbers updated to take an optional 3rd parameter

In [2]:
def add_numbers(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z

print(add_numbers(1, 2))
print(add_numbers(1, 2, 3))

3
6


In [3]:
def add_numbers(x, y, z=None, flag=False):
    if (flag):
        print('Flag is true!')
    if (z==None):
        return x + y
    else:
        return x + y + z
    
print(add_numbers(1, 2, flag=True))

Flag is true!
3


In [5]:
def add_numbers(x, y, z=None, flag=False):
    if (flag):
        print('Flag is true!')
    if (z==None):
        return x + y
    else:
        return x + y + z
    
print(add_numbers(1, 2))
print(add_numbers(1, 2,3))

3
6



Assign function add_numbers to variable a.

In [8]:
def add_numbers(x,y):
    return x+y

a = add_numbers
a(1,2)

3

In [9]:
add_numbers(1,8)

9

# 2. Types and Sequences

In [10]:
type('This is a string')

str

In [11]:
type(None)

NoneType

In [12]:
type(1)

int

In [13]:
type(1.0)

float

In [14]:
type(add_numbers)

function

Tuples are an immutable data structure (cannot be altered).

In [15]:
x = (1, 'a', 2, 'b')
type(x)

tuple

Lists are a mutable data structure.

In [16]:
x = [1, 'a', 2, 'b']
type(x)

list

In [17]:
x.append(3.3)
print(x)

[1, 'a', 2, 'b', 3.3]


In [18]:
for item in x:
    print(item)

1
a
2
b
3.3


In [19]:
i=0
while( i != len(x) ):
    print(x[i])
    i = i + 1

1
a
2
b
3.3



Use + to concatenate lists.

In [21]:
[1,2] + [3,4]

[1, 2, 3, 4]


Use * to repeat lists.

In [22]:
[1]*3

[1, 1, 1]


Use the in operator to check if something is inside a list.

In [23]:
1 in [1, 2, 3]

True

In [24]:
x = 'This is a string'
print(x[0]) #first character
print(x[0:1]) #first character, but we have explicitly set the end character
print(x[0:2]) #first two characters

T
T
Th


In [26]:
x[-1]

'g'

In [27]:
x[::-1]

'gnirts a si sihT'

In [28]:
x[-4:-2]

'ri'

In [29]:
x[:3]

'Thi'

In [30]:
x[3:]

's is a string'

In [31]:
firstname = 'Christopher'
lastname = 'Brooks'

print(firstname + ' ' + lastname)
print(firstname*3)
print('Chris' in firstname)

Christopher Brooks
ChristopherChristopherChristopher
True


In [32]:
firstname = 'Christopher Arthur Hansen Brooks'.split(' ')[0] # [0] selects the first element of the list
lastname = 'Christopher Arthur Hansen Brooks'.split(' ')[-1] # [-1] selects the last element of the list
print(firstname)
print(lastname)

Christopher
Brooks



Make sure you convert objects to strings before concatenating.

In [33]:
'Chris' + 2

TypeError: Can't convert 'int' object to str implicitly

In [34]:
'Chris' + str(2)

'Chris2'

In [35]:
x = {'Christopher Brooks': 'brooksch@umich.edu', 'Bill Gates': 'billg@microsoft.com'}
x['Christopher Brooks'] # Retrieve a value by using the indexing operator


'brooksch@umich.edu'

In [38]:
x['Kevyn Collins-Thompson'] = 1
x['Kevyn Collins-Thompson']

1

In [39]:
x['Kevyn Collins-Thompson'] = None
x['Kevyn Collins-Thompson']

In [40]:
x

{'Bill Gates': 'billg@microsoft.com',
 'Christopher Brooks': 'brooksch@umich.edu',
 'Kevyn Collins-Thompson': None}

In [41]:
x['Kevyn Collins-Thompson']

In [42]:
print(x['Kevyn Collins-Thompson'])

None



Iterate over all of the keys:

In [43]:
for name in x:
    print(x[name])

None
brooksch@umich.edu
billg@microsoft.com



Iterate over all of the values:

In [44]:
for email in x.values():
    print(email)

None
brooksch@umich.edu
billg@microsoft.com



Iterate over all of the items in the list:

In [45]:
for name, email in x.items():
    print(name)
    print(email)

Kevyn Collins-Thompson
None
Christopher Brooks
brooksch@umich.edu
Bill Gates
billg@microsoft.com



You can unpack a sequence into different variables:

In [46]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu')
fname, lname, email = x

In [47]:
fname

'Christopher'

In [48]:
lname

'Brooks'

Make sure the number of values you are unpacking matches the number of variables being assigned.

In [49]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu', 'Ann Arbor')
fname, lname, email = x

ValueError: too many values to unpack (expected 3)

# 3.  More on Strings

In [50]:
print('Chris' + 2)

TypeError: Can't convert 'int' object to str implicitly

In [51]:
print('Chris' + str(2))

Chris2


In [52]:
sales_record = {
'price': 3.24,
'num_items': 4,
'person': 'Chris'}

sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'

print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))

Chris bought 4 item(s) at a price of 3.24 each for a total of 12.96


# 4. Reading and Writing CSV files

csv.Dictreader reads each row of our csv file as a dictionary. len shows that our list is comprised of 234 dictionaries.

In [72]:
import csv

%precision 2

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))  #mpg is a dictionary
    
mpg[:3] # The first three dictionaries in our list.

[{'': '1',
  'class': 'compact',
  'cty': '18',
  'cyl': '4',
  'displ': '1.8',
  'drv': 'f',
  'fl': 'p',
  'hwy': '29',
  'manufacturer': 'audi',
  'model': 'a4',
  'trans': 'auto(l5)',
  'year': '1999'},
 {'': '2',
  'class': 'compact',
  'cty': '21',
  'cyl': '4',
  'displ': '1.8',
  'drv': 'f',
  'fl': 'p',
  'hwy': '29',
  'manufacturer': 'audi',
  'model': 'a4',
  'trans': 'manual(m5)',
  'year': '1999'},
 {'': '3',
  'class': 'compact',
  'cty': '20',
  'cyl': '4',
  'displ': '2',
  'drv': 'f',
  'fl': 'p',
  'hwy': '31',
  'manufacturer': 'audi',
  'model': 'a4',
  'trans': 'manual(m6)',
  'year': '2008'}]

In [73]:
import pandas as pd
data = pd.read_csv('mpg.csv')
data.head(5)

Unnamed: 0 manufacturer model  displ  year  cyl       trans drv  cty  hwy  \
0           1         audi    a4    1.8  1999    4    auto(l5)   f   18   29   
1           2         audi    a4    1.8  1999    4  manual(m5)   f   21   29   
2           3         audi    a4    2.0  2008    4  manual(m6)   f   20   31   
3           4         audi    a4    2.0  2008    4    auto(av)   f   21   30   
4           5         audi    a4    2.8  1999    6    auto(l5)   f   16   26   

  fl    class  
0  p  compact  
1  p  compact  
2  p  compact  
3  p  compact  
4  p  compact

In [74]:
with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))

In [75]:
mpg

[{'': '1',
  'class': 'compact',
  'cty': '18',
  'cyl': '4',
  'displ': '1.8',
  'drv': 'f',
  'fl': 'p',
  'hwy': '29',
  'manufacturer': 'audi',
  'model': 'a4',
  'trans': 'auto(l5)',
  'year': '1999'},
 {'': '2',
  'class': 'compact',
  'cty': '21',
  'cyl': '4',
  'displ': '1.8',
  'drv': 'f',
  'fl': 'p',
  'hwy': '29',
  'manufacturer': 'audi',
  'model': 'a4',
  'trans': 'manual(m5)',
  'year': '1999'},
 {'': '3',
  'class': 'compact',
  'cty': '20',
  'cyl': '4',
  'displ': '2',
  'drv': 'f',
  'fl': 'p',
  'hwy': '31',
  'manufacturer': 'audi',
  'model': 'a4',
  'trans': 'manual(m6)',
  'year': '2008'},
 {'': '4',
  'class': 'compact',
  'cty': '21',
  'cyl': '4',
  'displ': '2',
  'drv': 'f',
  'fl': 'p',
  'hwy': '30',
  'manufacturer': 'audi',
  'model': 'a4',
  'trans': 'auto(av)',
  'year': '2008'},
 {'': '5',
  'class': 'compact',
  'cty': '16',
  'cyl': '6',
  'displ': '2.8',
  'drv': 'f',
  'fl': 'p',
  'hwy': '26',
  'manufacturer': 'audi',
  'model': 'a4',
  'tran

In [76]:
len(mpg)

234

In [77]:
mpg[0].keys()

dict_keys(['', 'model', 'fl', 'displ', 'drv', 'cty', 'trans', 'year', 'class', 'manufacturer', 'cyl', 'hwy'])

In [78]:
mpg.keys()

AttributeError: 'list' object has no attribute 'keys'

#Find Avg city fuel economy across all cars

In [84]:
sum(float(d['cty']) for d in mpg)/len(mpg) #float() 2 convert string into float

16.86

find the average hwy fuel economy across all cars.

In [85]:
sum(float(d['hwy']) for d in mpg) / len(mpg)

23.44

 return the unique values for the number of cylinders the cars in our dataset have

In [86]:
cylinders = set(d['cyl'] for d in mpg)
cylinders

{'4', '5', '6', '8'}

grouping the cars by number of cylinder, and finding the average cty mpg for each group

In [91]:
CityMpgByCyl = []

for c in cylinders: # iterate over all the cylinder levels
    summpg = 0      #suming up mpg values by initialising it as 0
    cyltypecount = 0 #counting no. of values for each cyllinder type
    for d in mpg: # iterate over all dictionaries
        if d['cyl'] == c: # if the cylinder level type matches,
            summpg += float(d['cty']) # add the cty mpg
            cyltypecount += 1 # increment the count
    CityMpgByCyl.append((c, summpg / cyltypecount)) # append the tuple ('cylinder', 'avg mpg')

CityMpgByCyl.sort(key=lambda x: x[0])
CityMpgByCyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

return the unique values for the class types in our dataset.

In [92]:
vehicleclass = set(d['class'] for d in mpg) 
vehicleclass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

 find the average hwy mpg for each class of vehicle in our dataset.

In [93]:
HwyMpgByClass = []

for t in vehicleclass: # iterate over all the vehicle classes
    summpg = 0
    vclasscount = 0
    for d in mpg: # iterate over all dictionaries
        if d['class'] == t: # if the cylinder amount type matches,
            summpg += float(d['hwy']) # add the hwy mpg
            vclasscount += 1 # increment the count
    HwyMpgByClass.append((t, summpg / vclasscount)) # append the tuple ('class', 'avg mpg')

HwyMpgByClass.sort(key=lambda x: x[1])
HwyMpgByClass

[('pickup', 16.88),
 ('suv', 18.13),
 ('minivan', 22.36),
 ('2seater', 24.80),
 ('midsize', 27.29),
 ('subcompact', 28.14),
 ('compact', 28.30)]

# 5. Dates and Times

In [94]:
import datetime as dt
import time as tm

time returns the current time in seconds since the Epoch. (January 1st, 1970)

In [95]:
tm.time()

1560864798.38

In [99]:
1560864798.38/(60*60*24*365)

49.49

timestamp to datetime.

In [100]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2019, 6, 18, 19, 4, 56, 169258)

Handy datetime attributes:

In [101]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second 

(2019, 6, 18, 19, 4, 56)

timedelta is a duration expressing the difference between two dates.

In [102]:
delta = dt.timedelta(days = 100) # create a timedelta of 100 days
delta

datetime.timedelta(100)

date.today returns the current local date.

In [103]:
today = dt.date.today()

In [104]:
today - delta

datetime.date(2019, 3, 10)

In [105]:
today > today-delta # compare dates

True

# 6. Objects and map()

In [106]:
class Person:
    department = 'School of Information' #a class variable

    def set_name(self, new_name): #a method
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [107]:
person = Person()
person.set_name('Christopher Brooks')
person.set_location('Ann Arbor, MI, USA')
print('{} live in {} and works in the department {}'.format(person.name, person.location, person.department))

Christopher Brooks live in Ann Arbor, MI, USA and works in the department School of Information


mapping the min function between two lists

In [112]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2)
cheapest

In [113]:
for item in cheapest:
    print(item)

9.0
11.0
12.34
2.01


In [114]:
list(cheapest)

[]

# 7. Lambda and List Comprehensions

In [115]:
my_function = lambda a, b, c : a + b

In [116]:
my_function(1, 2, 3)

3

In [118]:
my_list = []
for number in range(0, 1000):
    if number % 2 == 0:
        my_list.append(number)
# my_list

In [120]:
my_list = [number for number in range(0,1000) if number % 2 == 0]
# my_list

# 8. Numerical Python (NumPy)

Create a list and convert it to a numpy array

In [122]:
import numpy as np
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

Or just pass in a list directly

In [4]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

Pass in a list of lists to create a multidimensional array.

In [124]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

Use the shape method to find the dimensions of the array. (rows, columns)

In [125]:
m.shape

(2, 3)


arange returns evenly spaced values within a given interval.

In [126]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])


reshape returns an array with the same data with a new shape.

In [127]:
n = n.reshape(3, 5) # reshape array to be 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

linspace returns evenly spaced numbers over a specified interval.

In [128]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

resize changes the shape and size of array in-place.

In [129]:
o.resize(3, 3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

ones returns a new array of given shape and type, filled with ones.



In [130]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

zeros returns a new array of given shape and type, filled with zeros.

In [131]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])


eye returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [132]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])


diag extracts a diagonal or constructs a diagonal array.

In [133]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])


Create an array using repeating list (or see np.tile)

In [137]:
np.array([1, 2, 3] * 5)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])


Repeat elements of an array using repeat.

In [136]:
np.repeat([1, 2, 3], 5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3])

Combining Arrays

In [138]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

Use vstack to stack arrays in sequence vertically (row wise).

In [139]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

use hstack to stack arrays in sequence horizontally (column wise).

In [140]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

# 9. Operations


In [141]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [142]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[0.25 0.4  0.5 ]


In [143]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

[1 4 9]


Dot Product:


In [144]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32

In [145]:
z = np.array([y, y**2])
print(len(z)) # number of rows of array

2


In [146]:
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [6]:
y

array([4, 5, 6])

In [9]:
# transposing arrays. Transposing permutes the dimensions of the array.

In [10]:
import numpy as np
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

 shape of array z is (2,3) before transposing.

In [12]:
z.shape

(2, 3)

.T to get the transpose.

In [13]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [14]:
z.T.shape

(3, 2)

In [15]:
z.shape

(2, 3)

.dtype to see the data type of the elements in the array.

In [16]:
z.dtype

dtype('int64')

.astype to cast to a specific type.

In [17]:
z = z.astype('f')
z.dtype

dtype('float32')

# 10. Math Functions

In [18]:
a = np.array([-4, -2, 1, 3, 5])

In [19]:
a

array([-4, -2,  1,  3,  5])

In [20]:
a.sum()

3

In [21]:
a.max()

5

In [22]:
a.min()

-4

In [23]:
a.mean()

0.6

In [24]:
a.std()

3.2619012860600183

argmax and argmin return the index of the maximum and minimum values in the array.

In [25]:
a.argmax()

4

In [26]:
a.argmin()

0

# 11.Indexing / Slicing 

In [27]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [28]:
np.arange(13)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

get the value at a specific index. Remember that indexing starts at 0.

In [29]:
s[0], s[4], s[-1]

(0, 16, 144)

Use : to indicate a range. array[start:stop]

Leaving start or stop empty will default to the beginning/end of the array.

In [30]:
s[1:5]

array([ 1,  4,  9, 16])

In [31]:
s[-4:]

array([ 81, 100, 121, 144])

A second : can be used to indicate step-size. array[start:stop:stepsize]

Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

In [32]:
s[-5::-2]

array([64, 36, 16,  4,  0])

In [33]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

Use bracket notation to slice: array[row, column]

In [34]:
r[2, 2]

14

And use : to select a range of rows or columns

In [35]:
r[3, 3:6]

array([21, 22, 23])

 we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.

In [36]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

This is a slice of the last row, and only every other element.

In [37]:
r[-1, ::2]

array([30, 32, 34])

conditional indexing. Here we are selecting values from the array that are greater than 30. (Also see np.where)

In [38]:
r[r > 30]

array([31, 32, 33, 34, 35])

Here we are assigning all values in the array that are greater than 30 to the value of 30.

In [39]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

# 12. Copying Data

In [40]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [41]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [42]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

r has also been changed!

To avoid this, use r.copy to create a copy that will not affect the original array

In [44]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [45]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


In [48]:
r_copy[:1]

array([[10, 10, 10, 10, 10, 10]])

In [50]:
r_copy[:]

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

# 12. Iterating Over Arrays

create a new 4 by 3 array of random numbers 0-9.

In [51]:
test = np.random.randint(0, 10, (4,3))
test

array([[5, 7, 4],
       [9, 2, 3],
       [2, 1, 6],
       [3, 3, 4]])

In [53]:
len(test)

4


Iterate by row:

In [52]:
for row in test:
    print(row)

[5 7 4]
[9 2 3]
[2 1 6]
[3 3 4]


Iterate by index:

In [54]:
for i in range(len(test)):
    print(test[i])

[5 7 4]
[9 2 3]
[2 1 6]
[3 3 4]


Iterate by row and index:

In [55]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [5 7 4]
row 1 is [9 2 3]
row 2 is [2 1 6]
row 3 is [3 3 4]


Use zip to iterate over multiple iterables.

In [56]:
test2 = test**2
test2

array([[25, 49, 16],
       [81,  4,  9],
       [ 4,  1, 36],
       [ 9,  9, 16]])

In [57]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[5 7 4] + [25 49 16] = [30 56 20]
[9 2 3] + [81  4  9] = [90  6 12]
[2 1 6] + [ 4  1 36] = [ 6  2 42]
[3 3 4] + [ 9  9 16] = [12 12 20]
